# Generated by Django 3.2.9 on 2022-02-27 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('post_id', models.IntegerField(blank=True, default=1)),
                ('Author', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('pubDate', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(default='Description')),
                ('work', models.CharField(blank=True, max_length=150)),
                ('education', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/profileImage')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('Chats', models.ManyToManyField(blank=True, null=True, related_name='chat', to='chat.Chatroom')),
                ('Following', models.ManyToManyField(blank=True, null=True, related_name='flowwers', to=settings.AUTH_USER_MODEL)),
                ('saved_posts', models.ManyToManyField(blank=True, null=True, related_name='SavedPosts', to='users.SavedPosts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
