# Generated by Django 3.2.9 on 2022-02-21 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Followes',
            new_name='Following',
        ),
    ]
