# Generated by Django 3.2.9 on 2022-02-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_followes_profile_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='SavedPosts', to='users.SavedPosts'),
        ),
    ]
