# Generated by Django 3.2.9 on 2022-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220221_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedposts',
            name='post_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
