# Generated by Django 3.2.9 on 2022-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_savedposts_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedposts',
            name='Author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='savedposts',
            name='pubDate',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='savedposts',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
